phone_brand = input("Enter Phone Brand: ")
phone_series = input("Enter Phone Series: ")
phone_storage = input("Enter Phone Storage: ")
phone_color = input("Enter Phone Color: ")
phone_price = input("Enter Phone Price: ")

print("===========================================")
print("            MOBILE PRODUCT          ")
print("===========================================")
print("Phone Brand: ", phone_brand)
print("Phone Series: ", phone_series)
print("Phone Storage: ", phone_storage)
print("Phone Color: ", phone_color)
print("Product Price: ", phone_price)
print("============================================")